#!/bin/bash

# color variables
r='\033[0;31m'
g='\033[0;32m'
y='\033[0;33m'
b='\033[0;34m'
m='\033[0;35m'
c='\033[0;36m'
# Clear the color after that
w='\033[0m'

STOPERROR="${r}Error: Stopped (dr) Drupal Composer Remove command!${w}"
PRESSENTER="[Press ${g}ENTER${w} or ${g}RETURN${w} to go ahead. PRESS ${g}CTRL/C${w} to stop]"

if [[ ! -d "vendor/composer" ]]; then
  printf "\n${STOPERROR}\nAre we in project root? The ${g}vendor/composer${w} directory is missing here in path.\n\n"
  exit 1
elif [[ ! -f "composer.json" ]]; then
  printf "\n${STOPERROR}\nAre we in prohect root? The ${g}composer.json${w} file does not exist here in path.\n\n"
  exit 1
elif [ "$#" -eq 0 ]; then
  printf "\n${STOPERROR}\nArguments Count: 0 - No arguments provided.\n\n"
  exit 1
fi

# To fix confusing arguments input like 1, 2,3 4 5
# so that it will be interpreted like 1 2 3 4 5 (as 5 arguments)
# we do some string split replace and prepare an array.
EXT=$@
if [[ $EXT == *","* ]] ; then
  printf "\nSeems that you used ${r}comma to provide multiple arguments.${w}\nDo you want to go ahead with seperated arguments? ${PRESSENTER}"
  read -p " ... "
  EXT=$(sed 's/,/, /g' <<<"$EXT")
  EXT=$(sed 's/,//g' <<<"$EXT")
fi
  EXT=$(sed 's/  / /g' <<<"$EXT")

IFS=' '
read -ra ARGS <<< "$EXT"

printf "\nDo you want to ${g}disable the extension in Drupal${w} first via Drush (pmu) before removing via Composer? "
read -p " Y(es)/N(o): " REPLY

if [[ "$REPLY" =~ ^([yY][eE][sS]|[yY])$ ]] ; then
  drush pmu $(for i in "${ARGS[@]}"; do printf " $i" ; done)
else
  printf "\n${g}Ok, Let's go ahead removing via Composer without uninstalling.${w}\n"
fi
composer remove $(for i in "${ARGS[@]}"; do printf " drupal/$i" ; done)

printf "\n${g}Done!${w}\n"
exit 0
